### ISSUE TITLE
Frontend: Review modal doesn't work

### ISSUE THREAD

**Issue by billmn** [owldesign/QARR#48]
Hi @owldesign,
when I click on "Write a Review" on frontend I see these errors in console:

![Schermata 2022-02-22 alle 16 11 08](https://user-images.githubusercontent.com/779534/155161699-ea2b4672-e0a2-4ca7-879b-8014ce121ffe.png)

These errors makes the plugin unusable as it is not possible to insert reviews.

Please can you help me?

**Comment by owldesign** [comment]
Can you show how you're using this on the frond end?

**Comment by billmn** [comment]
Sure, this is the code:

```
{% if craft.app.plugins.isPluginEnabled('qarr') %}
    <div id="review">
        {{ craft.qarr.display(product, {
            limit: 3,
            questions: false,
        }) }}
    </div>
{% endif %}
```

**Comment by owldesign** [comment]
Thanks, can you also please tell me which version of Craft you are using?

Looks like some "wise" decision was made to move Craft related calls to within Garnish library here: https://github.com/craftcms/cms/commit/5714ad6fd243bacdd85c142ba19b0b760c1dde38

Looking into fix now.

**Comment by billmn** [comment]
I'm using Craft CMS 3.7.33

Thank you!

**Comment by owldesign** [comment]
Ok from what I can gather, Craft is trying to do some accessibility stuff within the Garnish js, thus included Craft scripts within garnish Modal. Not sure if this will be final since I dont see this line `Craft.trapFocusWithin(this.$container);` in the original source here https://github.com/pixelandtonic/garnishjs/blob/v0.1.48/src/Modal.js

Anyways, instead of using Craft's `GarnishAsset::class` I opted to just using the garnish scripts from source.

Please update plugin and verify all back to normal?

**Comment by billmn** [comment]
Now it works fine, thank you!
